import type { CareRecipient, CareRecord, AlertNotification } from '../types'

export const demoCareRecipient: CareRecipient = {
  id: 'demo-recipient-1',
  userId: 'demo-user-1',
  name: 'Setsuko Tanaka',
  birthDate: '1948-05-15',
  gender: 'female',
  careLevel: 'care2',
  primaryDoctor: 'Dr. Taro Yamada',
  careManager: 'Hanako Sato',
  careManagerContact: '03-1234-5678',
  notes: 'Mild dementia. Taking medication for hypertension.',
  createdAt: new Date(),
  updatedAt: new Date(),
}

export const demoUser = {
  id: 'demo-user-1',
  email: 'keiko.tanaka@example.com',
  name: 'Yu',
  prefecture: 'Tokyo',
}

export const demoRecords: CareRecord[] = [
  {
    id: 'rec-1',
    userId: 'demo-user-1',
    careRecipientId: 'demo-recipient-1',
    recordDate: '2026-03-05',
    recordTime: '08:00',
    rawInput: 'Ate about half of breakfast. Seemed a little low on energy. Used the toilet twice.',
    structuredData: {
      meal: { breakfast: 'Ate approximately half', lunch: 'Not recorded', dinner: 'Not recorded', hydration: 'Not recorded' },
      elimination: { urine_count: 2, stool: 'Not recorded' },
      sleep: { hours: null, quality: 'Not recorded' },
      medication: { taken: null, notes: 'Not recorded' },
      physical: { temperature: null, pain: 'Not recorded', edema: 'Not recorded', other: 'Not recorded' },
      mental: { mood: 'A little low on energy', cognition: 'Not recorded', behavior: 'Not recorded' },
      fall_risk: 'Not recorded',
      special_notes: '',
      care_given: ['Breakfast assistance'],
    },
    photos: [],
    status: 'saved',
    createdAt: new Date('2026-03-05T08:00:00'),
    updatedAt: new Date('2026-03-05T08:00:00'),
  },
  {
    id: 'rec-2',
    userId: 'demo-user-1',
    careRecipientId: 'demo-recipient-1',
    recordDate: '2026-03-06',
    recordTime: '07:30',
    rawInput: 'No appetite. Ate almost nothing at breakfast. Woke up twice during the night. Some confusion noted.',
    structuredData: {
      meal: { breakfast: 'Ate almost nothing', lunch: 'Not recorded', dinner: 'Not recorded', hydration: 'Not recorded' },
      elimination: { urine_count: null, stool: 'Not recorded' },
      sleep: { hours: null, quality: 'Woke up twice during the night' },
      medication: { taken: null, notes: 'Not recorded' },
      physical: { temperature: null, pain: 'Not recorded', edema: 'Not recorded', other: 'Not recorded' },
      mental: { mood: 'Poor appetite', cognition: 'Mild confusion', behavior: 'Not recorded' },
      fall_risk: 'Not recorded',
      special_notes: 'Appetite loss continuing',
      care_given: ['Breakfast assistance'],
    },
    photos: [],
    status: 'saved',
    createdAt: new Date('2026-03-06T07:30:00'),
    updatedAt: new Date('2026-03-06T07:30:00'),
  },
  {
    id: 'rec-3',
    userId: 'demo-user-1',
    careRecipientId: 'demo-recipient-1',
    recordDate: '2026-03-07',
    recordTime: '07:45',
    rawInput: 'No appetite again today. Managed to drink a small amount of fluids. Expression seems distant and unfocused.',
    structuredData: {
      meal: { breakfast: 'Barely ate', lunch: 'Not recorded', dinner: 'Not recorded', hydration: 'Small amount taken' },
      elimination: { urine_count: null, stool: 'Not recorded' },
      sleep: { hours: null, quality: 'Not recorded' },
      medication: { taken: null, notes: 'Not recorded' },
      physical: { temperature: null, pain: 'Not recorded', edema: 'Not recorded', other: 'Not recorded' },
      mental: { mood: 'Distant and unfocused', cognition: 'Slow to respond', behavior: 'Not recorded' },
      fall_risk: 'Not recorded',
      special_notes: 'Day 3 of appetite loss. Cognitive changes noted.',
      care_given: ['Breakfast assistance', 'Hydration support'],
    },
    photos: [],
    status: 'saved',
    createdAt: new Date('2026-03-07T07:45:00'),
    updatedAt: new Date('2026-03-07T07:45:00'),
  },
]

export const demoAlerts: AlertNotification[] = [
  {
    id: 'alert-1',
    userId: 'demo-user-1',
    careRecipientId: 'demo-recipient-1',
    type: 'health_alert',
    title: 'Appetite has declined for 3 consecutive days',
    description: 'Appetite loss has continued since March 5th. There is a risk of dehydration and malnutrition. Reporting to the care manager is recommended.',
    severity: 'high',
    suggestion: 'We recommend reporting the situation to the care manager (Hanako Sato). Would you like to draft a message?',
    read: false,
    actionUrl: '/guide',
    createdAt: new Date('2026-03-07T08:00:00'),
  },
  {
    id: 'alert-2',
    userId: 'demo-user-1',
    careRecipientId: 'demo-recipient-1',
    type: 'renewal_reminder',
    title: 'Long-term care certification renewal is approaching',
    description: 'Setsuko Tanaka\'s long-term care certification expires at the end of April 2026. Let\'s start preparing for the renewal process.',
    severity: 'medium',
    suggestion: 'Would you like to review the renewal procedure guide? We can help you prepare the necessary documents.',
    read: false,
    actionUrl: '/guide',
    createdAt: new Date('2026-03-06T09:00:00'),
  },
  {
    id: 'alert-3',
    userId: 'demo-user-1',
    careRecipientId: 'demo-recipient-1',
    type: 'report_ready',
    title: 'February monthly report draft has been created',
    description: 'A draft report for the care manager has been created based on February 2026 care records. Please review and edit as needed.',
    severity: 'low',
    suggestion: 'Would you like to review the report?',
    read: false,
    actionUrl: '/report/new',
    createdAt: new Date('2026-03-01T09:00:00'),
  },
]
